### ISSUE TITLE
Bad API Key

### ISSUE THREAD

**Issue by TheGeneral2277** [IAHispano/Applio-API#1]
I am trying to connect to the kits API using Applio. I am using this url: https://api.applio.org/key=(secret)/generateToken. I am using the Token that I generated on the website and getting a "Bad Api Key" Error response. What should I do to connect?

**Comment by bygimenez** [comment]
To generate a token **you need an administrator API KEY**. This is not a bug/error.

![Image](https://github.com/IAHispano/Applio-API/assets/67287120/ff2bc750-70a5-4dc6-a94d-9b4f83e0820e)
